[package]
name = "rs-gandi-dns-dynip"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
isahc = { version = "1.6", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
